services:
  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    env_file:
      - ./backend/.env

    ports: ["3000:3000"]
    environment: [NODE_ENV=production]

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    ports: ["80:80", "443:443"]
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend


  certbot:
    image: certbot/certbot
    volumes: ["./certbot/conf:/etc/letsencrypt","./certbot/www:/var/www/certbot"]

