#lightweight version of node
FROM node:20-alpine AS builder

#create app dir
WORKDIR /app 

#copy package files 
COPY package*.json ./

#install only production packages
RUN npm ci 

#copy folder contents
COPY . .

RUN npm run build

#set production envs
ENV NODE_ENV=production

FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY --from=builder /app/dist ./dist

#create non root user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

#change ownership
RUN chown -R appuser:appgroup /app

#change user
USER appuser

#expose port
EXPOSE 3000

#start app
CMD ["node", "dist/index.js"]