#lightweight version of node
FROM node:20-alpine

#create app dir
WORKDIR /app 

#copy package files 
COPY package*.json ./

#install only production packages
RUN npm ci --omit=dev

#copy folder contents
COPY . .

#set production envs
ENV NODE_ENV=production

#export port
EXPOSE 3000

#create non root user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

#change ownership
RUN chown -R appuser:appgroup /app

#change user
USER appuser

#start app
CMD ["node", "server.js"]